blank_issues_enabled: false
contact_links:
  - name: Security Contact
    url: https://github.com/binGhzal/CloudMoor/security/advisories/new
    about: Use GitHub advisories for private, time-sensitive security disclosures.
  - name: Roadmap & Governance Docs
    url: https://github.com/binGhzal/CloudMoor/tree/main/docs
    about: Review the plan, spec, and tasks before filing feature requests.
