name: "Feature request"
description: "Propose a new idea or enhancement for CloudMoor"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Have a feature idea? Tell us how it supports the milestone roadmap. Please reference relevant sections of `docs/plan.md` or `docs/tasks.md`.
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checks
      options:
        - label: I have read the current roadmap in `docs/plan.md`
          required: true
        - label: I have searched existing issues and discussions for similar requests
          required: true
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature or enhancement.
      placeholder: Support mounting Google Drive read-only
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem does this feature solve? Include personas or workflows when possible.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Outline your idea, including APIs, CLI commands, UX changes, or architectural notes.
      placeholder: |
        - Extend connector interface with ...
        - Add CLI flag `--read-only`
        - Update Web UI wizard accordingly
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or workarounds
      description: Describe any alternative approaches you considered.
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies and risks
      description: Note related tickets, external systems, or risks to call out.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links to prototypes, diagrams, or decision logs.
    validations:
      required: false
